### ISSUE TITLE
maximum call stack exceeded at lexicographic-integer

### ISSUE THREAD

**Issue by Ivshti** [mafintosh/multi-master-merge#11]
```
/Users/ivogeorgiev/multipass-torrent/node_modules/multi-master-merge/node_modules/scuttleup/node_modules/lexicographic-integer/index.js:4
function pack (n, enc) {
              ^
RangeError: Maximum call stack size exceeded
    at pack (/Users/ivogeorgiev/multipass-torrent/node_modules/multi-master-merge/node_modules/scuttleup/node_modules/lexicographic-integer/index.js:4:15)
    at pack (/Users/ivogeorgiev/multipass-torrent/node_modules/multi-master-merge/node_modules/scuttleup/node_modules/lexicographic-integer/index.js:41:33)
    at pack (/Users/ivogeorgiev/multipass-torrent/node_modules/multi-master-merge/node_modules/scuttleup/node_modules/lexicographic-integer/index.js:41:33)
    at pack (/Users/ivogeorgiev/multipass-torrent/node_modules/multi-master-merge/node_modules/scuttleup/node_modules/lexicographic-integer/index.js:41:33)
```

Pack is a recursive function, so obviously it has reached a point where it exceeds the maximum call stack.

**Update** the issue is induced from .pack being passed a NaN, which in it's turn is induced by my GC code at Ivshti/multi-master-merge, but it's still an issue with upstream mmm because the entry.prev value  in index contains stuff like
``
 [ 'undefined@undefined', 'undefined@undefined' ]
``

**Comment by Ivshti** [comment]
Totally disgerard that - a result of passing wrong stuff to .merge
